language: python
python:
- 3.5
before_install:
- openssl aes-256-cbc -K $encrypted_5961923817ae_key -iv $encrypted_5961923817ae_iv -in deploy-key.enc -out deploy-key -d
- mv deploy-key ~/.ssh/deploy-key
- chmod u=rw,og= ~/.ssh/deploy-key
- echo "Host github.com" >> ~/.ssh/config
- echo "HostName github.com" >> ~/.ssh/config
- echo "IdentityFile ~/.ssh/deploy-key" >> ~/.ssh/config
- echo "User git" >> ~/.ssh/config
- git remote set-url origin git@github.com:marco-c/grcov-test.git
- git fetch origin -f gh-pages:gh-pages
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script:
- flake8 .
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && python go.py && ghp-import -n -p -m "Report" report'
