sudo: required
language: python
python:
- 3.5
before_install:
- openssl aes-256-cbc -K $encrypted_5961923817ae_key -iv $encrypted_5961923817ae_iv -in deploy-key.enc -out deploy-key -d
- mv deploy-key ~/.ssh/deploy-key
- chmod u=rw,og= ~/.ssh/deploy-key
- echo "Host github.com" >> ~/.ssh/config
- echo "HostName github.com" >> ~/.ssh/config
- echo "IdentityFile ~/.ssh/deploy-key" >> ~/.ssh/config
- echo "User git" >> ~/.ssh/config
- git remote set-url origin git@github.com:marco-c/grcov-test.git
- git fetch origin -f gh-pages:gh-pages
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
- sudo -E apt-get -yq update &>> ~/apt-get-update.log
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-6 g++-6
- git clone https://github.com/linux-test-project/lcov.git && cd lcov && sudo make install && cd ..
- mkdir -p symlinks
- ln -s /usr/bin/g++-6 symlinks/g++
- ln -s /usr/bin/gcc-6 symlinks/gcc
- ln -s /usr/bin/gcov-6 symlinks/gcov
#- wget https://github.com/marco-c/grcov/releases/download/v0.1.3/grcov-linux-x86_64.tar.bz2
- tar xf grcov-linux-x86_64.tar.bz2
- cp grcov symlinks/grcov
script:
- export PATH=$PWD/symlinks:$PATH
- flake8 .
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && python go.py && ghp-import -n -p -m "Report" report'
- cat error
- ls -al
