sudo: required
language: rust
rust:
  - nightly
before_install:
  - openssl aes-256-cbc -K $encrypted_5961923817ae_key -iv $encrypted_5961923817ae_iv -in deploy-key.enc -out deploy-key -d
  - mv deploy-key ~/.ssh/deploy-key
  - chmod u=rw,og= ~/.ssh/deploy-key
  - echo "Host github.com" >> ~/.ssh/config
  - echo "HostName github.com" >> ~/.ssh/config
  - echo "IdentityFile ~/.ssh/deploy-key" >> ~/.ssh/config
  - echo "User git" >> ~/.ssh/config
  - git remote set-url origin git@github.com:marco-c/grcov-test.git
  - git fetch origin -f gh-pages:gh-pages
install:
  - sudo pip install -r requirements.txt
  - sudo pip install -r test-requirements.txt
  - mkdir -p symlinks
  - git clone https://github.com/linux-test-project/lcov.git && cd lcov && make install DESTDIR=symlinks && cd ..
  - ln -s /usr/bin/g++-6 symlinks/g++
  - ln -s /usr/bin/gcc-6 symlinks/gcc
  - ln -s /usr/bin/gcov-6 symlinks/gcov
  - git clone https://github.com/marco-c/grcov && cd grcov && cargo build --release && cp target/release/grcov ../symlinks/grcov && cd ..
  - ls -al symlinks
  - lcov --version
  #- wget https://github.com/marco-c/grcov/releases/download/v0.1.3/grcov-linux-x86_64.tar.bz2
  #- cp grcov symlinks/grcov
script:
  - export PATH=$PWD/symlinks:$PWD/symlinks/bin:$PATH
  - flake8 .
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && python download-artifacts.py && python code-coverage.py && python generate-report.py && ghp-import -n -p -m "Report" report'
  - cat error
  - ls -al
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
